require 'mechanize'
require "rest_client"
require 'pry-nav'
require 'nokogiri'
require 'csv'

class Scraper 
	attr_reader :ids, :rows, :ids, :jurisdiction_name, :table_row, :office, :number, :district, :i
	def initialize
		@rows = []
	end

	def get_ocd_ids
		page = RestClient.get("https://raw.githubusercontent.com/opencivicdata/ocd-division-ids/master/identifiers/country-us/census_autogenerated/us_census_places.csv")
		noko = Nokogiri::HTML(page)
		@ids = noko.text.lines.select do |line|
			line =~ /state:ak/
		end.map do |line|
			line.gsub(/,.+/, '').gsub(/\n/, '')
		end
	end 

	def get_chart
		i = 37	
		#aurora is first at tr index 37
		#last tr is Hughes at index 516
		while i < 517 do 
			agent = Mechanize.new
			main_page = agent.get("http://www.elections.alaska.gov/vi_w_p_list_poll.php#37").parser
			@table_row = main_page.css('tr')[i]
			parse_municipality
			i += 1
		end
	end


	def parse_municipality
		if table_row.css('td')[1]
			@jurisdiction_name = table_row.css('td')[3].text.split(",").last.lstrip.downcase.split(" ").map(&:capitalize).join(" ")
			@number = table_row.css('td')[0].text
			@district = @number[0..1].to_i
			assign_to_office
		end

	end		

	def assign_to_office

		if district <= 36 && district >= 29
			office = "Region I Elections Office"
			phone = "(907) 465-3021"
		elsif (district >= 13 && district <= 28)
			office = "Region II Elections Office"
			phone = "(907) 522-8683"
		elsif district == 7 || district == 8 || (district >=10 && district <= 12)
			office = "Region II Elections Office"
			phone = "(907) 373-8952"
		elsif (district >= 1 && district <= 6) || district == 9
			office = "Region III Elections Office"
			phone = "(907) 451-2835"
		elsif (district >= 37 && district <= 40) 
			office = "Region IV Elections Office"
			phone = "(907) 443-5285"
		elsif district == 37 || district == 39 || district == 40

			if number[3] == "3"
				office = "Region III Elections Office"
				phone = "(907) 451-2835"

			elsif number[3] == "7" || number[3] == "9" || (number[3..5].to_i >= 2 && number[3..5].to_i <= 40)
				office = "Region IV Elections Office"
				phone = "(907) 443-5285"
			end

		end		
		id = match_ocd
		if id 
			@rows << [jurisdiction_name, "AK", office, phone, id]

		end
	end

	#def city_or_county	

		# if @jurisdiction_name.include?("City") 
		# 	first_column = @jurisdiction_name
		# 	second_column = ""
		# else
		# 	first_column = ""
		# 	second_column = @jurisdiction_name
		# end

	#end


	# def get_website
	# 	first_url = newpage.css('#ctl00_ContentPlaceHolder1_usrLocalityRegContact_lblClickableURL').text
	# 	second_url = newpage.css('#ctl00_ContentPlaceHolder1_usrLocalityElectionBoard_lblClickableURL').text
	# 	if first_url != ""
	# 		website = first_url
	# 	elsif second_url != ""
	# 		website = second_url
	# 	else 
	# 		website = ""
	# 	end
	# 	website

	# end

	def match_ocd
		name = @jurisdiction_name.gsub(" ", "_").gsub("&", "and").gsub(/ No\..*/, "")
		
		#id = @ids.reject { |line|	line =~ /place:/ }.find { |id| id =~ /county:#{name}/i } || @ids.find { |id| id =~ /place:#{name}/i }

		id = @ids.find { |id| id =~ /#{name}/i } 

	end

	def write_into_CSV_file
		@rows.uniq!
		@rows.sort_by! {|row| row[0]}
		CSV.open("spreadsheet.csv", "wb") do |csv|
			@rows.map do |line|
				csv << line
			end
		end
	end

end

a = Scraper.new
a.get_ocd_ids
a.get_chart
a.write_into_CSV_file
