require 'mechanize'
require "rest_client"
require 'pry-nav'
require 'nokogiri'
require 'csv'

class Scraper 
	attr_reader :ids, :rows, :ids, :jurisdiction_name, :table_row, :office, :number, :district
	def initialize
		@rows = []
	end

	def get_ocd_ids
		page = RestClient.get("https://raw.githubusercontent.com/opencivicdata/ocd-division-ids/master/identifiers/country-us/census_autogenerated/us_census_places.csv")
		noko = Nokogiri::HTML(page)
		@ids = noko.text.lines.select do |line|
			line =~ /state:al/
		end
	end 

	def get_chart
		i = 37	
		#aurora is first at tr index 37
		#last tr is Hughest at index 516
		while i < 517 do 
			agent = Mechanize.new
			main_page = agent.get("http://www.elections.alaska.gov/vi_w_p_list_poll.php#37").parser
			@table_row = main_page.css('tr')[i]
			parse_municipality
			i += 1
		end
	end


	def parse_municipality
		@jurisdiction_name = table_row.css('td')[1].text.downcase.split(" ").map(&:capitalize).join(" ")
		@number = table_row.css('td')[0].text
		@district = @number[0..1].to_i
		assign_to_office

		@rows << [first_column, second_column, "VA", office, phone, match_ocd]

	end		

	def assign_to_office

		if district <= 26 && district >=29
			office = "Region I Elections Office"
		elsif district <= 13 && district >= 28
			office = "Region II Elections Office"
		elsif (district >= 1 && district >= 6) || district == 9
			office = "Region III Elections Office"
		elsif district == 37 
		elsif district == 39
		elsif district == 40
		end		

	end

	#def city_or_county	

		# if @jurisdiction_name.include?("City") 
		# 	first_column = @jurisdiction_name
		# 	second_column = ""
		# else
		# 	first_column = ""
		# 	second_column = @jurisdiction_name
		# end

	#end


	# def get_website
	# 	first_url = newpage.css('#ctl00_ContentPlaceHolder1_usrLocalityRegContact_lblClickableURL').text
	# 	second_url = newpage.css('#ctl00_ContentPlaceHolder1_usrLocalityElectionBoard_lblClickableURL').text
	# 	if first_url != ""
	# 		website = first_url
	# 	elsif second_url != ""
	# 		website = second_url
	# 	else 
	# 		website = ""
	# 	end
	# 	website

	# end

	# def match_ocd
	# 	if @jurisdiction_name.include?("County")
	# 		name = @jurisdiction_name.rstrip.gsub(/\scounty/i, "").gsub(" ", "_").gsub("&", "and")
	# 		id = @ids.reject do |line|
	# 				line =~ /place:/
	# 			end.map do |line|
	# 			line
	# 		end.find do |id|
	# 			id =~ /county:#{name}/i
	# 		end
	# 		if id
	# 			id.gsub(/,.+/, '').gsub(/\n/, '')
	# 		end
	# 	elsif @jurisdiction_name.include?("City")
	# 		name = @jurisdiction_name.gsub(/\scity/i, "").gsub(" ", "_")
	# 		id = @ids.find do |id|
	# 			id =~ /place:#{name}/i
	# 		end
	# 		if id 
	# 			id.gsub(/,.+/, '').gsub(/\n/, '')
	# 		end
	# 	else 
	# 		id = ""
	# 	end

	# end

	def write_into_CSV_file
		CSV.open("spreadsheet.csv", "wb") do |csv|
			@rows.map do |line|
				csv << line
			end
		end
	end

end

a = Scraper.new
a.get_ocd_ids
a.get_chart
a.write_into_CSV_file
